
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


public class Daily_Transaction extends javax.swing.JFrame {

    dbhelper db=new dbhelper();
    
    /**
     * Creates new form Daily_Transaction
     */
    public Daily_Transaction() {
        initComponents();
        AutoIncrement();
//        //db.getTable(name, s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtLitre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbOil_Type = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        dt = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(100, 101, 165));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(246, 233, 107));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Daily Transaction");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 270, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 100));

        jPanel3.setBackground(new java.awt.Color(246, 233, 107));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Amount");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 90, -1));

        txtRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRateFocusLost(evt);
            }
        });
        txtRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRateActionPerformed(evt);
            }
        });
        jPanel3.add(txtRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 230, 30));
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 230, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Date");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 50, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Oil Type");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 90, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Litre");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 90, -1));
        jPanel3.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 230, 30));
        jPanel3.add(txtLitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 230, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Rate");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 90, -1));

        cmbOil_Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petrol", "Disel" }));
        jPanel3.add(cmbOil_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 230, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Id");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 30, -1));

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel3.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 90, -1));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 90, -1));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 90, -1));
        jPanel3.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 230, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 950, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 970, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRateActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        AutoIncrement();
       Validate();
       SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        
        String  date= sdf.format(dt.getDate()) ;

        System.out.println(date);
       
        db.InsertData("insert into daily_transaction(Id,date,oil_type,litre,rate,amount) values('"+txtID.getText()+"','"+date+"','"+cmbOil_Type.getSelectedItem().toString()+"','"+txtLitre.getText()+"','"+txtRate.getText()+"','"+txtAmount.getText()+"')");
        db.updateRecord("Update Stock set  Qty=Qty -'"+Double.parseDouble(txtLitre.getText().toString()) +"' Where OilType='"+cmbOil_Type.getSelectedItem().toString()+"'");
        clearText();
        AutoIncrement();
//db.getTable(jTableSupplier, "select * from daily_transaction");
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your hatock sndling code here:
        db.updateRecord("update daily_transaction set oil_type='"+cmbOil_Type.getSelectedItem().toString()+"',litre='"+txtLitre.getText()+"',rate='"+txtRate.getText()+"',amount='"+txtAmount.getText()+"' where id='"+txtID.getText()+"'");
    }//GEN-LAST:event_updateActionPerformed

    private void txtRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRateFocusLost
cal();
    }//GEN-LAST:event_txtRateFocusLost

    public void AutoIncrement()
    {
        try
        {
        String s="select MAX(id) from daily_transaction";
        db.DataFound(s);
        int i=0;
        while(db.rs.next())
        {
           i=db.rs.getInt(1);
        } 
       txtID.setText(String.valueOf(i+1));
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    
     public void Validate()
    {
        if(txtID.getText().equals("")||txtLitre.getText().equals("")||txtRate.getText().equals("")||txtAmount.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
            return;
        }
    }
     
      public void clearText()
     {
         txtID.setText("");
        txtLitre.setText("");
        txtRate.setText("");
        txtAmount.setText("");
     }
      public void cal()
      {
          double ltr,rate,amt;
          ltr=Double.parseDouble(txtLitre.getText().toString());
          rate=Double.parseDouble(txtRate.getText().toString());
          
          amt=ltr*rate;
          txtAmount.setText(String.valueOf(amt));
      }
     
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daily_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daily_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daily_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daily_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daily_Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> cmbOil_Type;
    private com.toedter.calendar.JDateChooser dt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton save;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLitre;
    private javax.swing.JTextField txtRate;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
