
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Purchase_Item extends javax.swing.JFrame {
    String  date;
    dbhelper db=new dbhelper();

    /**
     * Creates new form Purchase_Item
     */
    public Purchase_Item() {
        initComponents();
      AutoIncrement();
        db.getTable(table_purchaseitem, "select * from purchase_item");
        db.FillCombo(cmbSupplierName, "select name from supplier", "name");
//        db.getTable(jTable1, "select * from Purchase_Item");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_purchaseitem = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTotAmt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtLitre = new javax.swing.JTextField();
        txtPurchaseRate = new javax.swing.JTextField();
        cmbOilType = new javax.swing.JComboBox<>();
        cmbSupplierName = new javax.swing.JComboBox<>();
        cancel = new javax.swing.JButton();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        dt = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(100, 101, 165));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(246, 233, 107));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_purchaseitem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Date", "Supplier Name", "Oil Type", "Litre", "Purchase Rate", "Total Amount"
            }
        ));
        jScrollPane1.setViewportView(table_purchaseitem);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 580, 510));

        jPanel3.setBackground(new java.awt.Color(246, 233, 107));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel8.setText("Purchase Item");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 310, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1090, 100));

        jPanel4.setBackground(new java.awt.Color(246, 233, 107));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Total Amount");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 140, 30));

        txtTotAmt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTotAmtFocusLost(evt);
            }
        });
        txtTotAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotAmtActionPerformed(evt);
            }
        });
        jPanel4.add(txtTotAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 210, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Id");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 40, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Date");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Supplier Name");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 150, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("OilType");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Litre");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Purchase Rate");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 150, 30));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel4.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 210, 30));
        jPanel4.add(txtLitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 210, 30));

        txtPurchaseRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPurchaseRateFocusLost(evt);
            }
        });
        txtPurchaseRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurchaseRateActionPerformed(evt);
            }
        });
        jPanel4.add(txtPurchaseRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 210, 30));

        cmbOilType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petrol", "Disel" }));
        jPanel4.add(cmbOilType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 210, 30));

        jPanel4.add(cmbSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 142, 210, 30));

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel4.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel4.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel4.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));
        jPanel4.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 210, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 500, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1110, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotAmtActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtPurchaseRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurchaseRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurchaseRateActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
        
        try
        {
         AutoIncrement();
       Validate();
       
       SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        
        date= sdf.format(dt.getDate()) ;

        System.out.println(date);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Date is not correct");
        }
          db.InsertData("insert into purchase_item(Id,date,supplier_name,oil_type,litre,purchase_rate,total_amount) values('"+txtID.getText()+"','"+date+"','"+cmbSupplierName.getSelectedItem().toString()+"','"+cmbOilType.getSelectedItem().toString()+"','"+txtLitre.getText()+"','"+txtPurchaseRate.getText()+"','"+txtTotAmt.getText()+"')");
         //db.getTable(jTableSupplier, "select * from daily_transaction");
         clearText();
         AutoIncrement();
         
          db.updateRecord("Update Stock set  Qty=Qty + '"+Double.parseDouble(txtLitre.getText().toString()) +"' Where OilType='"+cmbOilType.getSelectedItem().toString()+"'");
          db.getTable(table_purchaseitem, "select * from purchase_item");
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        db.updateRecord("update purchase_item set supplier_name='"+cmbSupplierName.getSelectedItem().toString()+"',oil_type='"+cmbOilType.getSelectedItem().toString()+"',litre='"+txtLitre.getText()+"',purchase_rate='"+txtPurchaseRate.getText()+"',total_amount='"+txtTotAmt.getText()+"' where id='"+txtID.getText()+"'");
         db.getTable(table_purchaseitem, "select * from purchase_item");
    }//GEN-LAST:event_updateActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
            this.dispose();      
    }//GEN-LAST:event_cancelActionPerformed

    private void txtPurchaseRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPurchaseRateFocusLost
        cal();
    }//GEN-LAST:event_txtPurchaseRateFocusLost

    private void txtTotAmtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTotAmtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotAmtFocusLost
    
    public void AutoIncrement()
    {
        try
        {
        String s="select MAX(Id) from purchase_item";
        db.DataFound(s);
        int i=0;
        while(db.rs.next())
        {
           i=db.rs.getInt(1);
        } 
       txtID.setText(String.valueOf(i+1));
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    
     public void Validate()
    {
        if(txtID.getText().equals("")||txtLitre.getText().equals("")||txtPurchaseRate.getText().equals("")||txtTotAmt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
            return;
        }
    }
     
      public void clearText()
     {
         txtID.setText("");
        txtLitre.setText("");
        txtLitre.setText("");
        txtPurchaseRate.setText("");
        txtTotAmt.setText("");
        
     }
      
      public void cal()
      {
          double ltr,rate,amt;
          ltr=Double.parseDouble(txtLitre.getText().toString());
          rate=Double.parseDouble(txtPurchaseRate.getText().toString());
          
          amt=ltr*rate;
          txtTotAmt.setText(String.valueOf(amt));
      }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase_Item().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> cmbOilType;
    private javax.swing.JComboBox<String> cmbSupplierName;
    private com.toedter.calendar.JDateChooser dt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save;
    private javax.swing.JTable table_purchaseitem;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLitre;
    private javax.swing.JTextField txtPurchaseRate;
    private javax.swing.JTextField txtTotAmt;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
