
import java.io.InputStream;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Report_Option extends javax.swing.JFrame {
    dbhelper db=new dbhelper();
     String m_where;
    String m_report_source = "/PetrolpumpManagement/";
    String m_sql_stmt;
    Map parametersMap = new HashMap();  

    /**
     * Creates new form Report_Option
     */
    public Report_Option() {
        initComponents();
    }
    
    public void Show()
    {
         try {
            DBUtilities dbUtilities = new DBUtilities();
            InputStream is = getClass().getResourceAsStream(m_report_source);

            JRDesignQuery jrDesignQuery = new JRDesignQuery();
            jrDesignQuery.setText(m_sql_stmt);

            JasperDesign jasperDesign = JRXmlLoader.load(is);
            jasperDesign.setQuery(jrDesignQuery);

            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametersMap, dbUtilities.getConnection());
            JasperViewer.viewReport(jasperPrint, false);

        } catch (SQLException | JRException e) {
            System.out.println("Exception message " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblAddRate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTransaction = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblEmployee = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblExpenses = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblPurchase = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblSupplier = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(100, 101, 165));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddRate.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblAddRate.setForeground(new java.awt.Color(102, 0, 102));
        lblAddRate.setText("Rate Report");
        lblAddRate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddRateMouseClicked(evt);
            }
        });
        jPanel2.add(lblAddRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 80));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTransaction.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTransaction.setForeground(new java.awt.Color(102, 0, 102));
        lblTransaction.setText("Trasaction Report");
        lblTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTransactionMouseClicked(evt);
            }
        });
        jPanel3.add(lblTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 240, 80));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmployee.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblEmployee.setForeground(new java.awt.Color(102, 0, 102));
        lblEmployee.setText("Employee Report");
        lblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseClicked(evt);
            }
        });
        jPanel4.add(lblEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 240, 80));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExpenses.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblExpenses.setForeground(new java.awt.Color(102, 0, 102));
        lblExpenses.setText("Expenses Report");
        lblExpenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExpensesMouseClicked(evt);
            }
        });
        jPanel5.add(lblExpenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 240, 80));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPurchase.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblPurchase.setForeground(new java.awt.Color(102, 0, 102));
        lblPurchase.setText("Purchase Report");
        lblPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPurchaseMouseClicked(evt);
            }
        });
        jPanel6.add(lblPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 240, 80));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSupplier.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblSupplier.setForeground(new java.awt.Color(102, 0, 102));
        lblSupplier.setText("Supplier Report");
        lblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSupplierMouseClicked(evt);
            }
        });
        jPanel7.add(lblSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 240, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddRateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddRateMouseClicked
         m_report_source = "rptRate.jrxml";
        m_sql_stmt = "SELECT add_rate.`id` AS add_rate_id, add_rate.`date` AS add_rate_date, add_rate.`rate` AS add_rate_rate, add_rate.`item_type` AS add_rate_item_type FROM `add_rate` add_rate";
   Show();
    }//GEN-LAST:event_lblAddRateMouseClicked

    private void lblTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTransactionMouseClicked
         m_report_source = "rptTransaction.jrxml";
        m_sql_stmt = "SELECT daily_transaction.`id` AS daily_transaction_id, daily_transaction.`date` AS daily_transaction_date, daily_transaction.`oil_type` AS daily_transaction_oil_type, daily_transaction.`litre` AS daily_transaction_litre, daily_transaction.`rate` AS daily_transaction_rate, daily_transaction.`amount` AS daily_transaction_amount FROM `daily_transaction` daily_transaction";
   Show();
    }//GEN-LAST:event_lblTransactionMouseClicked

    private void lblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseClicked
         m_report_source = "rptEmployee.jrxml";
        m_sql_stmt = "SELECT employee.`id` AS employee_id, employee.`name` AS employee_name, employee.`address` AS employee_address, employee.`mobile_no` AS employee_mobile_no FROM `employee` employee";
   Show();
    }//GEN-LAST:event_lblEmployeeMouseClicked

    private void lblExpensesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExpensesMouseClicked
         m_report_source = "rptExpenses.jrxml";
        m_sql_stmt = "SELECT expense.`id` AS expense_id, expense.`date` AS expense_date, expense.`expense_type` AS expense_expense_type, expense.`description` AS expense_description, expense.`amount` AS expense_amount FROM `expense` expense";
   Show();
    }//GEN-LAST:event_lblExpensesMouseClicked

    private void lblPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPurchaseMouseClicked
         m_report_source = "rptPurchase.jrxml";
        m_sql_stmt = "SELECT purchase_item.`id` AS purchase_item_id, purchase_item.`date` AS purchase_item_date, purchase_item.`supplier_name` AS purchase_item_supplier_name, purchase_item.`oil_type` AS purchase_item_oil_type, purchase_item.`litre` AS purchase_item_litre, purchase_item.`purchase_rate` AS purchase_item_purchase_rate, purchase_item.`total_amount` AS purchase_item_total_amount FROM `purchase_item` purchase_item";
   Show();
    }//GEN-LAST:event_lblPurchaseMouseClicked

    private void lblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMouseClicked
         m_report_source = "rptSupplier.jrxml";
        m_sql_stmt = "SELECT supplier.`id` AS supplier_id, supplier.`name` AS supplier_name, supplier.`address` AS supplier_address, supplier.`company_name` AS supplier_company_name, supplier.`company_address` AS supplier_company_address, supplier.`mobile_no` AS supplier_mobile_no FROM `supplier` supplier";
   Show();
    }//GEN-LAST:event_lblSupplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report_Option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblAddRate;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblExpenses;
    private javax.swing.JLabel lblPurchase;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTransaction;
    // End of variables declaration//GEN-END:variables
}
