
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Supplier extends javax.swing.JFrame {
    dbhelper db=new dbhelper();
    /**
     * Creates new form Supplier1
     */
    public Supplier() {
        initComponents();
         AutoIncrement();
        db.getTable(table_Supplier, "select * from supplier");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_Mobile3 = new javax.swing.JTextField();
        txt_CompanyAddr = new javax.swing.JTextField();
        txt_CompanyName = new javax.swing.JTextField();
        txt_Address = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        txt_Id = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Supplier = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(100, 101, 165));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(246, 233, 107));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel19.setText("mobile no");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 120, 20));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel20.setText("id");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 20));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel21.setText("name");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, 20));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel22.setText("address");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, 20));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel23.setText("company name");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 160, 20));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel24.setText("company address");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 180, 20));

        txt_Mobile3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Mobile3ActionPerformed(evt);
            }
        });
        jPanel9.add(txt_Mobile3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 210, 30));

        txt_CompanyAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CompanyAddrActionPerformed(evt);
            }
        });
        jPanel9.add(txt_CompanyAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 232, 210, 30));

        txt_CompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CompanyNameActionPerformed(evt);
            }
        });
        jPanel9.add(txt_CompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 210, 30));

        txt_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AddressActionPerformed(evt);
            }
        });
        jPanel9.add(txt_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 210, 30));

        txt_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NameActionPerformed(evt);
            }
        });
        jPanel9.add(txt_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 210, 30));

        txt_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdActionPerformed(evt);
            }
        });
        jPanel9.add(txt_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 32, 210, 30));

        btnCancel.setText("cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel9.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        btnSave.setText("save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel9.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        btnUpdate.setText("update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel9.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 490, 400));

        jPanel10.setBackground(new java.awt.Color(246, 233, 107));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel25.setText("Supplier");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 230, 60));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1050, 100));

        jPanel11.setBackground(new java.awt.Color(246, 233, 107));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_Supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "address", "company name", "company address", "mobile no"
            }
        ));
        jScrollPane1.setViewportView(table_Supplier);

        jPanel11.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 320));

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 550, 400));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1080, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1136, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Mobile3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Mobile3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Mobile3ActionPerformed

    private void txt_CompanyAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CompanyAddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CompanyAddrActionPerformed

    private void txt_CompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CompanyNameActionPerformed

    private void txt_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AddressActionPerformed

    private void txt_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NameActionPerformed

    private void txt_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        AutoIncrement();
       Validate();

        db.InsertData("insert into supplier(Id,name,address,company_name,company_address,mobile_no) values('"+txt_Id.getText()+"','"+txt_Name.getText()+"','"+txt_Address.getText()+"','"+txt_CompanyName.getText()+"','"+txt_CompanyAddr.getText()+"','"+txt_Mobile3.getText()+"')");
        db.getTable(table_Supplier, "select * from supplier");
        clearText();
        AutoIncrement();
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        db.updateRecord("update supplier set name='"+txt_Name.getText()+"',address='"+txt_Address.getText()+"',company_name='"+txt_CompanyName.getText()+"',company_address='"+txt_CompanyAddr.getText()+"',mobile_no='"+txt_Mobile3.getText()+"' where id='"+txt_Id.getText()+"'");
        db.getTable(table_Supplier, "select * from supplier");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    public void AutoIncrement()
    {
        try
        {
        String s="select MAX(Id) from supplier";
        db.DataFound(s);
        int i=0;
        while(db.rs.next())
        {
           i=db.rs.getInt(1);
        } 
        txt_Id.setText(String.valueOf(i+1));
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    
     public void Validate()
    {
        if(txt_Id.getText().equals("")||txt_Name.getText().equals("")||txt_Address.getText().equals("")||txt_CompanyName.getText().equals("")||txt_CompanyAddr.getText().equals("")||txt_Mobile3.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
            return;
        }
    }
     
     public void clearText()
     {
         txt_Id.setText("");
        txt_Name.setText("");
        txt_Address.setText("");
        txt_CompanyName.setText("");
        txt_CompanyAddr.setText("");
        txt_Mobile3.setText("");
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_Supplier;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JTextField txt_CompanyAddr;
    private javax.swing.JTextField txt_CompanyName;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Mobile3;
    private javax.swing.JTextField txt_Name;
    // End of variables declaration//GEN-END:variables
}
